package ActorLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import com.mbeddr.core.modules.behavior.ITypeDeclaration__BehaviorDescriptor;
import ActorLanguage.behavior.IState__BehaviorDescriptor;
import jetbrains.mps.lang.traceable.behavior.UnitConcept__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class ActorScriptCPU_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.createUnitInfo();
    int maxAddress = 0;
    for (SNode actor : ListSequence.fromList(SNodeOperations.getNodeDescendants(ctx.getPrimaryInput(), CONCEPTS.CreateActor$Uv, false, new SAbstractConcept[]{}))) {
      if (SPropertyOperations.getInteger(actor, PROPS.address$DqJ_) > maxAddress) {
        maxAddress = SPropertyOperations.getInteger(actor, PROPS.address$DqJ_);
      }
    }

    // includes
    List<String> headers = ListSequence.fromList(new ArrayList<String>());

    tgs.append("#include <ROOT-Sim.h>");
    tgs.newLine();
    ListSequence.fromList(headers).addElement("ROOT-Sim");

    for (SNode type : Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.types$lVcp), CONCEPTS.ExternalType$Bi))) {
      if (!(ListSequence.fromList(headers).contains(SPropertyOperations.getString(type, PROPS.header$$WII)))) {
        ListSequence.fromList(headers).addElement(SPropertyOperations.getString(type, PROPS.header$$WII));
        tgs.append("#include <");
        tgs.append(SPropertyOperations.getString(type, PROPS.header$$WII));
        tgs.append(".h>");
        tgs.newLine();
      }
    }

    for (SNode function : Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.externalFunctions$bWTb), CONCEPTS.ExternalFunctionPrototype$n3))) {
      if (!(ListSequence.fromList(headers).contains(SPropertyOperations.getString(function, PROPS.header$7lfc)))) {
        ListSequence.fromList(headers).addElement(SPropertyOperations.getString(function, PROPS.header$7lfc));
        tgs.append("#include <");
        tgs.append(SPropertyOperations.getString(function, PROPS.header$7lfc));
        tgs.append(".h>");
        tgs.newLine();
      }
    }

    // define number of LPs
    tgs.append("#ifndef NUM_LPS");
    tgs.newLine();
    tgs.append("#define NUM_LPS ");
    tgs.append(String.valueOf(maxAddress + 1));
    tgs.newLine();
    tgs.append("#endif");
    tgs.newLine();
    tgs.newLine();

    // define number of threads to 0 (max threads available)
    tgs.append("#ifndef NUM_THREADS");
    tgs.newLine();
    tgs.append("#define NUM_THREADS 0");
    tgs.newLine();
    tgs.append("#endif");
    tgs.newLine();
    tgs.newLine();

    // custom events
    tgs.append("enum event_types {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    for (SNode customEvent : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.customEvents$eDRO)).where((it) -> !(SPropertyOperations.getString(it, PROPS.name$MnvL).equals("LP_INIT")) && !(SPropertyOperations.getString(it, PROPS.name$MnvL).equals("LP_FINI")))) {
      tgs.indent();
      tgs.append(SPropertyOperations.getString(customEvent, PROPS.name$MnvL));
      tgs.append(",");
      tgs.newLine();
    }
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("};");
    tgs.newLine();


    for (SNode item : SNodeOperations.ofConcept(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.configuration$6ery), CONCEPTS.GlobalConstant$pG)) {
      tgs.appendNode(item);
    }
    tgs.newLine();


    // envelope struct definition
    tgs.append("typedef struct Envelope {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("lp_id_t sender;");
    tgs.newLine();
    tgs.indent();
    tgs.append("float priority;");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("} Envelope;");
    tgs.newLine();
    tgs.newLine();

    // message struct definition
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.messageDefinition$$rsX));
    tgs.newLine();

    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.topology$GORc) != null)) {
      tgs.append("struct topology *topology;");
      tgs.newLine();
    }
    for (SNode item : SNodeOperations.ofConcept(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.configuration$6ery), CONCEPTS.GlobalVarDecl$3_)) {
      tgs.appendNode(item);
    }
    tgs.newLine();

    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.randomStuff$BMch));
    tgs.newLine();

    for (SNode externalFunction : Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.externalFunctions$bWTb), CONCEPTS.ExternalFunction$kh))) {
      tgs.appendNode(externalFunction);
      tgs.newLine();
      tgs.newLine();
    }

    tgs.newLine();

    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.topology$GORc) != null)) {
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.topology$GORc));
    }

    Behaviors.behaviors(SNodeOperations.ofConcept(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.behaviors$VQhG), CONCEPTS.CreateBehavior$iN), ctx);



    /*
      ProcessEvent function
      This function contains the steps defined in each behavior to process messages

    */

    tgs.append("void ProcessEvent(lp_id_t me, simtime_t now, unsigned event_type, const void *content, unsigned size, void *state_ptr)");
    tgs.newLine();
    tgs.append("{");
    tgs.newLine();

    ctx.getBuffer().area().increaseIndent();

    // invoke the specific behavior based on the address of the actor (i.e., the ID of the LP) that has received this message
    tgs.indent();
    tgs.append("switch(me) {");
    tgs.newLine();
    // Each message in the actor model has an associated event type (e.g., Event); the "append handle received event" operation executes a set of actions - defined in the actor model - based on such event type.

    for (SNode createActor : ListSequence.fromList(SNodeOperations.getNodeDescendants(ctx.getPrimaryInput(), CONCEPTS.CreateActor$Uv, false, new SAbstractConcept[]{})).where((it) -> !(SNodeOperations.isInstanceOf(SNodeOperations.getParent(it), CONCEPTS.CreateActors$rc)))) {
      ProcessEvent.handleReceivedEvent(SPropertyOperations.getInteger(createActor, PROPS.address$DqJ_), -1, SLinkOperations.getTarget(createActor, LINKS.behavior$1pSN), SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.customEvents$eDRO), true, ctx);
    }
    for (SNode createActors : ListSequence.fromList(SNodeOperations.getNodeDescendants(ctx.getPrimaryInput(), CONCEPTS.CreateActors$rc, false, new SAbstractConcept[]{}))) {
      ProcessEvent.handleReceivedEvent(SPropertyOperations.getInteger(ListSequence.fromList(SLinkOperations.getChildren(createActors, LINKS.actors$HQEA)).getElement(0), PROPS.address$DqJ_), SPropertyOperations.getInteger(ListSequence.fromList(SLinkOperations.getChildren(createActors, LINKS.actors$HQEA)).getElement(0), PROPS.address$DqJ_) + SPropertyOperations.getInteger(createActors, PROPS.number$$XD7) - 1, SLinkOperations.getTarget(createActors, LINKS.behavior$1pSN), SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.customEvents$eDRO), true, ctx);
    }

    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();

    // todo model specific
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL).contains("COMPADS")) {
      return;
    }

    // CanEnd
    tgs.append("boolean CanEnd(lp_id_t me, const void *snapshot) { return ((");
    tgs.appendNode(ITypeDeclaration__BehaviorDescriptor.createType_id3o2OLGv7CoR.invoke(IState__BehaviorDescriptor.getStructDeclaration_id7t$FNisxQwi.invoke(SLinkOperations.getTarget(ListSequence.fromList(SNodeOperations.getNodeDescendants(ctx.getPrimaryInput(), CONCEPTS.CreateActor$Uv, false, new SAbstractConcept[]{})).first(), LINKS.stateType$2Mnh))));
    tgs.append(" *)state)->canEnd; }");
    tgs.newLine();

    tgs.newLine();

    // configure simulation
    tgs.append("struct simulation_configuration conf = {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append(".lps = ");
    tgs.append(String.valueOf(maxAddress + 1));
    tgs.append(",");
    tgs.newLine();
    tgs.indent();
    tgs.append(".n_threads = 1,");
    tgs.newLine();
    tgs.indent();
    tgs.append(".termination_time = 0,");
    tgs.newLine();
    tgs.indent();
    tgs.append(".gvt_period = 1000,");
    tgs.newLine();
    tgs.indent();
    tgs.append(".log_level = LOG_INFO,");
    tgs.newLine();
    tgs.indent();
    tgs.append(".stats_file = \"stats\",");
    tgs.newLine();
    tgs.indent();
    tgs.append(".ckpt_interval = 0,");
    tgs.newLine();
    tgs.indent();
    tgs.append(".core_binding = true,");
    tgs.newLine();
    tgs.indent();
    tgs.append(".serial = false,");
    tgs.newLine();
    tgs.indent();
    tgs.append(".dispatcher = ProcessEvent,");
    tgs.newLine();
    tgs.indent();
    tgs.append(".committed = CanEnd,");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("};");
    tgs.newLine();
    tgs.newLine();

    // main function
    tgs.append("int main(int argc, char *argv[]) {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    // todo handle input parameters in a configurable way (defined by the overlying model)
    tgs.indent();
    tgs.append("if (argc != 4) {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("printf(\"Usage: %s <n_threads> <termination_time> <gvt_period>\", argv[0]);");
    tgs.newLine();
    tgs.indent();
    tgs.append("exit(1);");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    tgs.indent();
    tgs.append("conf.n_threads = atoi(argv[1]);");
    tgs.newLine();
    tgs.indent();
    tgs.append("conf.termination_time = atoi(argv[2]);");
    tgs.newLine();
    tgs.indent();
    tgs.append("conf.gvt_period = atoi(argv[3]);");
    tgs.newLine();

    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.topology$GORc) != null)) {
      tgs.indent();
      tgs.append("topology = InitializeTopology(TOPOLOGY_GRAPH, ");
      tgs.append(String.valueOf(maxAddress + 1));
      tgs.append(");");
      tgs.newLine();
    }

    tgs.newLine();
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.startupCode$I5MT) != null)) {
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.startupCode$I5MT));
    }
    tgs.newLine();

    tgs.indent();
    tgs.append("RootsimInit(&conf);");
    tgs.newLine();
    tgs.indent();
    tgs.append("int ret = RootsimRun();");
    tgs.newLine();

    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.topology$GORc) != null)) {
      tgs.indent();
      tgs.append("ReleaseTopology(topology);");
      tgs.newLine();
    }

    tgs.indent();
    tgs.append("return ret;");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();

    tgs.append("}");
    tgs.newLine();
    tgs.newLine();

    if (tgs.needPositions()) {
      tgs.fillUnitInfo(UnitConcept__BehaviorDescriptor.getUnitName_id4pl5GY7LKmR.invoke(SNodeOperations.cast(ctx.getPrimaryInput(), CONCEPTS.UnitConcept$1g)));
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty address$DqJ_ = MetaAdapterFactory.getProperty(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23364L, 0x13974e2681512c34L, "address");
    /*package*/ static final SProperty header$$WII = MetaAdapterFactory.getProperty(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x2e879cff63330806L, 0xbc4afff42e6671bL, "header");
    /*package*/ static final SProperty header$7lfc = MetaAdapterFactory.getProperty(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884e7a5fe9L, 0x6065ca884e7a6002L, "header");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty randomStuff$BMch = MetaAdapterFactory.getProperty(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0x9f540b99f7e7870L, "randomStuff");
    /*package*/ static final SProperty number$$XD7 = MetaAdapterFactory.getProperty(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x5d890eb3ec029424L, 0x5d890eb3ec029443L, "number");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept CreateActor$Uv = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23364L, "ActorLanguage.structure.CreateActor");
    /*package*/ static final SConcept ExternalType$Bi = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x2e879cff63330806L, "ActorLanguage.structure.ExternalType");
    /*package*/ static final SConcept ExternalFunctionPrototype$n3 = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884e7a5fe9L, "ActorLanguage.structure.ExternalFunctionPrototype");
    /*package*/ static final SConcept GlobalConstant$pG = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x32cd46c3579fd9e1L, "ActorLanguage.structure.GlobalConstant");
    /*package*/ static final SConcept GlobalVarDecl$3_ = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0xbc4afff405f7c4bL, "ActorLanguage.structure.GlobalVarDecl");
    /*package*/ static final SConcept ExternalFunction$kh = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x61da6c5c302aacc3L, "ActorLanguage.structure.ExternalFunction");
    /*package*/ static final SConcept CreateBehavior$iN = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x2176abe5743ae753L, "ActorLanguage.structure.CreateBehavior");
    /*package*/ static final SConcept CreateActors$rc = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x5d890eb3ec029424L, "ActorLanguage.structure.CreateActors");
    /*package*/ static final SInterfaceConcept UnitConcept$1g = MetaAdapterFactory.getInterfaceConcept(0x9ded098bad6a4657L, 0xbfd948636cfe8bc3L, 0x465516cf87c705a4L, "jetbrains.mps.lang.traceable.structure.UnitConcept");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink types$lVcp = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0x754f4cb23a308c63L, "types");
    /*package*/ static final SContainmentLink externalFunctions$bWTb = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0x61da6c5c302ab136L, "externalFunctions");
    /*package*/ static final SContainmentLink customEvents$eDRO = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0x1f52820f4a642248L, "customEvents");
    /*package*/ static final SContainmentLink configuration$6ery = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0xbc4afff405f7c51L, "configuration");
    /*package*/ static final SContainmentLink messageDefinition$$rsX = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0x1b883a660b9077f5L, "messageDefinition");
    /*package*/ static final SContainmentLink topology$GORc = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0x262cd812cfe6cc9dL, "topology");
    /*package*/ static final SContainmentLink behaviors$VQhG = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0x5d890eb3ebfeaec2L, "behaviors");
    /*package*/ static final SReferenceLink behavior$1pSN = MetaAdapterFactory.getReferenceLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884ef595cdL, 0x344e3e3ed823c988L, "behavior");
    /*package*/ static final SContainmentLink actors$HQEA = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x5d890eb3ec029424L, 0x2e933327a36608L, "actors");
    /*package*/ static final SReferenceLink stateType$2Mnh = MetaAdapterFactory.getReferenceLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884ef595cdL, 0x47ae2b741b264b71L, "stateType");
    /*package*/ static final SContainmentLink startupCode$I5MT = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0x32cd46c35a8fe3fbL, "startupCode");
  }
}
