package ActorLanguage.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import ActorLanguage.behavior.IState__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public abstract class Behaviors {
  public static void behaviors(Iterable<SNode> behaviors, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (final SNode behavior : Sequence.fromIterable(behaviors)) {

      if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(behavior), CONCEPTS.ActorScriptCPU$mu)) {
        /*
          CPU code

        */

        if ((SLinkOperations.getTarget(SLinkOperations.getTarget(behavior, LINKS.eventHandler$MLkf), LINKS.body$f8RW) != null) && ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(behavior, LINKS.eventHandler$MLkf), LINKS.body$f8RW), LINKS.statements$euTV)).isNotEmpty()) {
          tgs.append("static void ");
          tgs.append(SPropertyOperations.getString(behavior, PROPS.name$MnvL));
          tgs.append("(lp_id_t me, simtime_t now, void *");
          tgs.append(SPropertyOperations.getString(behavior, PROPS.receivedMessageName$AwKe));
          tgs.append(")");
          tgs.newLine();
          tgs.appendNode(SLinkOperations.getTarget(SLinkOperations.getTarget(behavior, LINKS.eventHandler$MLkf), LINKS.body$f8RW));
          tgs.newLine();
        }
      } else {
        /*
          GPU code

        */

        tgs.append("__device__");
        tgs.newLine();
        tgs.append("static void ");
        tgs.append(SPropertyOperations.getString(behavior, PROPS.name$MnvL));
        tgs.append("(uint64_t me, double now, Event *");
        tgs.append(SPropertyOperations.getString(behavior, PROPS.receivedMessageName$AwKe));
        tgs.append(")");
        tgs.newLine();
        tgs.append("{");
        tgs.newLine();
        ctx.getBuffer().area().increaseIndent();
        SNode stateStruct = IState__BehaviorDescriptor.getStructDeclaration_id7t$FNisxQwi.invoke(SLinkOperations.getTarget(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(SNodeOperations.cast(SNodeOperations.getParent(behavior), CONCEPTS.ActorScript$nz), LINKS.actorCreation$EA0a), CONCEPTS.ICreateActor$Ng)).findFirst((it) -> SLinkOperations.getTarget(it, LINKS.behavior$1pSN) == behavior), LINKS.stateType$2Mnh));

        // get random context
        tgs.indent();
        tgs.append("curandState_t *cr_state = &(");
        tgs.append(SPropertyOperations.getString(stateStruct, PROPS.name$MnvL));
        tgs.append("_nodes.cr_state[me]);");
        tgs.newLine();
        tgs.newLine();

        // load state
        tgs.indent();
        tgs.append("/* load state */");
        tgs.newLine();
        tgs.indent();
        tgs.append(SPropertyOperations.getString(stateStruct, PROPS.name$MnvL));
        tgs.append(" state = {");
        tgs.newLine();
        ctx.getBuffer().area().increaseIndent();
        for (SNode m : Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(stateStruct, LINKS.members$C59R), CONCEPTS.Member$J1))) {
          if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(m, LINKS.type$sXU3), CONCEPTS.StructType$B3) && SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(m, LINKS.type$sXU3), CONCEPTS.StructType$B3), LINKS.struct$WCsg), PROPS.name$MnvL).equals("rng_t")) {
            continue;
          }
          tgs.indent();
          tgs.append(".");
          tgs.append(SPropertyOperations.getString(m, PROPS.name$MnvL));
          tgs.append(" = ");
          tgs.append(SPropertyOperations.getString(stateStruct, PROPS.name$MnvL));
          tgs.append("_nodes.");
          tgs.append(SPropertyOperations.getString(m, PROPS.name$MnvL));
          tgs.append("[me],");
          tgs.newLine();
        }
        ctx.getBuffer().area().decreaseIndent();
        tgs.indent();
        tgs.append("};");
        tgs.newLine();

        for (SNode stmt : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(behavior, LINKS.eventHandler$MLkf), LINKS.body$f8RW), LINKS.statements$euTV))) {
          tgs.indent();
          tgs.appendNode(stmt);
          tgs.newLine();
        }

        // write state
        tgs.indent();
        tgs.append("/* store state */");
        tgs.newLine();
        for (SNode m : Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(stateStruct, LINKS.members$C59R), CONCEPTS.Member$J1))) {
          if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(m, LINKS.type$sXU3), CONCEPTS.StructType$B3) && SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(m, LINKS.type$sXU3), CONCEPTS.StructType$B3), LINKS.struct$WCsg), PROPS.name$MnvL).equals("rng_t")) {
            continue;
          }
          tgs.indent();
          tgs.append(SPropertyOperations.getString(stateStruct, PROPS.name$MnvL));
          tgs.append("_nodes.");
          tgs.append(SPropertyOperations.getString(m, PROPS.name$MnvL));
          tgs.append("[me] = ");
          tgs.append("state.");
          tgs.append(SPropertyOperations.getString(m, PROPS.name$MnvL));
          tgs.append(";");
          tgs.newLine();
        }

        ctx.getBuffer().area().decreaseIndent();
        tgs.append("}");
        tgs.newLine();
        tgs.newLine();
      }

    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty receivedMessageName$AwKe = MetaAdapterFactory.getProperty(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x2176abe5743ae753L, 0x5ef413f8f5ef4191L, "receivedMessageName");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink eventHandler$MLkf = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x2176abe5743ae753L, 0x35a5eccbf2f8e453L, "eventHandler");
    /*package*/ static final SContainmentLink body$f8RW = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x1b883a6609f93db2L, 0x3a16e3a9c7ad9954L, "body");
    /*package*/ static final SContainmentLink statements$euTV = MetaAdapterFactory.getContainmentLink(0xa9d696470840491eL, 0xbf392eb0805d2011L, 0x3a16e3a9c7ad9955L, 0x3a16e3a9c7ad9956L, "statements");
    /*package*/ static final SContainmentLink actorCreation$EA0a = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, 0x35a5eccbf2f23377L, "actorCreation");
    /*package*/ static final SReferenceLink behavior$1pSN = MetaAdapterFactory.getReferenceLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884ef595cdL, 0x344e3e3ed823c988L, "behavior");
    /*package*/ static final SReferenceLink stateType$2Mnh = MetaAdapterFactory.getReferenceLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884ef595cdL, 0x47ae2b741b264b71L, "stateType");
    /*package*/ static final SContainmentLink type$sXU3 = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x46a2a92ac61b183L, 0x46a2a92ac61b184L, "type");
    /*package*/ static final SReferenceLink struct$WCsg = MetaAdapterFactory.getReferenceLink(0xefda956e491e4f00L, 0xba1436af2f213ecfL, 0x58bef62304fc0a38L, 0x58bef62304fc0a39L, "struct");
    /*package*/ static final SContainmentLink members$C59R = MetaAdapterFactory.getContainmentLink(0xefda956e491e4f00L, 0xba1436af2f213ecfL, 0x6285e27d4ff6c9f5L, 0x6285e27d4ff7db92L, "members");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ActorScriptCPU$mu = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x46a144cd5bb2ddL, "ActorLanguage.structure.ActorScriptCPU");
    /*package*/ static final SConcept ActorScript$nz = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f23376L, "ActorLanguage.structure.ActorScript");
    /*package*/ static final SInterfaceConcept ICreateActor$Ng = MetaAdapterFactory.getInterfaceConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884ef595cdL, "ActorLanguage.structure.ICreateActor");
    /*package*/ static final SConcept StructType$B3 = MetaAdapterFactory.getConcept(0xefda956e491e4f00L, 0xba1436af2f213ecfL, 0x58bef62304fc0a38L, "com.mbeddr.core.udt.structure.StructType");
    /*package*/ static final SConcept Member$J1 = MetaAdapterFactory.getConcept(0xefda956e491e4f00L, 0xba1436af2f213ecfL, 0x51a277741cc50918L, "com.mbeddr.core.udt.structure.Member");
  }
}
