package QueryLanguage.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "QueryLanguage";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (concept.getName()) {
        case "ColumnRef":
          return Collections.<NodeFactory>singletonList(new ColumnRefFactory.NodeFactory_6649776843796618830());
        case "Script":
          return Collections.<NodeFactory>singletonList(new ScriptFactory.NodeFactory_5818081797687955067());
        case "SelectColumn":
          return Collections.<NodeFactory>singletonList(new SelectColumnFactory.NodeFactory_6649776843783650044());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

}
