package ActorLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Behavior extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Behavior() {
    super(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f26de9L, "Behavior", "r:a6f544b3-65b6-4da8-ad8a-228799e10ea8(ActorLanguage.structure)/3865756215865929193");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_HelloWorld_0 = new EnumerationDescriptor.MemberDescriptor("HelloWorld", "hello-world", 0x35a5eccbf2f26deaL, "r:a6f544b3-65b6-4da8-ad8a-228799e10ea8(ActorLanguage.structure)/3865756215865929194");
  private final EnumerationDescriptor.MemberDescriptor myMember_CustomMessage_0 = new EnumerationDescriptor.MemberDescriptor("CustomMessage", "custom-message", 0x35a5eccbf2f26debL, "r:a6f544b3-65b6-4da8-ad8a-228799e10ea8(ActorLanguage.structure)/3865756215865929195");
  private final EnumerationDescriptor.MemberDescriptor myMember_Idle_0 = new EnumerationDescriptor.MemberDescriptor("Idle", "idle", 0x35a5eccbf2f26deeL, "r:a6f544b3-65b6-4da8-ad8a-228799e10ea8(ActorLanguage.structure)/3865756215865929198");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x35a5eccbf2f26de9L, 0x35a5eccbf2f26deaL, 0x35a5eccbf2f26debL, 0x35a5eccbf2f26deeL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_HelloWorld_0, myMember_CustomMessage_0, myMember_Idle_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_HelloWorld_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "HelloWorld":
        return myMember_HelloWorld_0;
      case "CustomMessage":
        return myMember_CustomMessage_0;
      case "Idle":
        return myMember_Idle_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
