package ActorLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AbstractActor = 0;
  public static final int Actor = 1;
  public static final int ActorAction = 2;
  public static final int ActorScript = 3;
  public static final int BecomeBehavior = 4;
  public static final int Message = 5;
  public static final int SendMessage = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x10eda99958984cdeL, 0x9416196c5eca1268L);
    builder.put(0x35a5eccbf2f23308L, AbstractActor);
    builder.put(0x35a5eccbf2f23364L, Actor);
    builder.put(0x35a5eccbf2f8e44bL, ActorAction);
    builder.put(0x35a5eccbf2f23376L, ActorScript);
    builder.put(0x35a5eccbf2f26dfaL, BecomeBehavior);
    builder.put(0x35a5eccbf2f23371L, Message);
    builder.put(0x35a5eccbf2f26df2L, SendMessage);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
