package ActorLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AbstractActor = 0;
  public static final int AbstractBehavior = 1;
  public static final int Actor = 2;
  public static final int ActorAction = 3;
  public static final int ActorScript = 4;
  public static final int CreateBehavior = 5;
  public static final int CreateEnvelope = 6;
  public static final int CreateMessage = 7;
  public static final int CreatePayload = 8;
  public static final int Envelope = 9;
  public static final int Fetch = 10;
  public static final int Payload = 11;
  public static final int SelectBehavior = 12;
  public static final int SelectEnvelope = 13;
  public static final int SelectPayload = 14;
  public static final int SendMessage = 15;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x10eda99958984cdeL, 0x9416196c5eca1268L);
    builder.put(0x35a5eccbf2f23308L, AbstractActor);
    builder.put(0x619ceb9024127367L, AbstractBehavior);
    builder.put(0x35a5eccbf2f23364L, Actor);
    builder.put(0x35a5eccbf2f8e44bL, ActorAction);
    builder.put(0x35a5eccbf2f23376L, ActorScript);
    builder.put(0x2176abe5743ae753L, CreateBehavior);
    builder.put(0x2176abe574366687L, CreateEnvelope);
    builder.put(0x35a5eccbf2f23371L, CreateMessage);
    builder.put(0x2176abe574366688L, CreatePayload);
    builder.put(0x9de89b125c73205L, Envelope);
    builder.put(0x619ceb90241d8975L, Fetch);
    builder.put(0x4658738496c93a81L, Payload);
    builder.put(0x619ceb9024171024L, SelectBehavior);
    builder.put(0x9de89b125bf6283L, SelectEnvelope);
    builder.put(0x4658738496c93a82L, SelectPayload);
    builder.put(0x35a5eccbf2f26df2L, SendMessage);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
