package ActorLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class CreateActorReference_Constraints extends BaseConstraintsDescriptor {
  /*package*/ CreateActorReference_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.CreateActorReference$5e, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.actor$leqD, container, false, true);
    }
    @Override
    public boolean validate(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      return true;
    }
    @Override
    public void onReferenceSet(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      SLinkOperations.setTarget(SLinkOperations.getTarget(referenceNode, LINKS.actorReference$ovWr), LINKS.actor$BImE, newReferentNode);
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept CreateActorReference$5e = MetaAdapterFactory.getConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x2e933327617303L, "ActorLanguage.structure.CreateActorReference");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink actor$leqD = MetaAdapterFactory.getReferenceLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x2e933327617303L, 0x2e9333279305bfL, "actor");
    /*package*/ static final SContainmentLink actorReference$ovWr = MetaAdapterFactory.getContainmentLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x2e933327617303L, 0x2e9333277ec654L, "actorReference");
    /*package*/ static final SReferenceLink actor$BImE = MetaAdapterFactory.getReferenceLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x2e9333277ec5d1L, 0x2e9333277ec5d2L, "actor");
  }
}
