package ActorLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import ActorLanguage.behavior.ICreateActor__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class ICreateActor_Constraints extends BaseConstraintsDescriptor {
  /*package*/ ICreateActor_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.ICreateActor$Ng, initContext);
    record(new RD1(this));
    record(new RD2(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.stateType$2Mnh, container, false, true);
    }
    @Override
    public boolean validate(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      return true;
    }
    @Override
    public void onReferenceSet(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      SLinkOperations.setTarget(referenceNode, LINKS.stateType$2Mnh, newReferentNode);
      ICreateActor__BehaviorDescriptor.setStateTypeInSelectedBehavior_id3XCCzVTGGIW.invoke(referenceNode);
    }
  }
  /*package*/ static final class RD2 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD2(ConstraintsDescriptor container) {
      super(LINKS.behavior$1pSN, container, false, true);
    }
    @Override
    public boolean validate(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      return true;
    }
    @Override
    public void onReferenceSet(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      SLinkOperations.setTarget(referenceNode, LINKS.behavior$1pSN, newReferentNode);
      ICreateActor__BehaviorDescriptor.setStateTypeInSelectedBehavior_id3XCCzVTGGIW.invoke(referenceNode);
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept ICreateActor$Ng = MetaAdapterFactory.getInterfaceConcept(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884ef595cdL, "ActorLanguage.structure.ICreateActor");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink stateType$2Mnh = MetaAdapterFactory.getReferenceLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884ef595cdL, 0x47ae2b741b264b71L, "stateType");
    /*package*/ static final SReferenceLink behavior$1pSN = MetaAdapterFactory.getReferenceLink(0x10eda99958984cdeL, 0x9416196c5eca1268L, 0x6065ca884ef595cdL, 0x344e3e3ed823c988L, "behavior");
  }
}
