package QueryLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AggregateFunctionTypes extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AggregateFunctionTypes() {
    super(0x26d1395b1ee643adL, 0xb522c0cdd699ded3L, 0x7642dbf63a6e5138L, "AggregateFunctionTypes", "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/8521615295527145784");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_COUNT_0 = new EnumerationDescriptor.MemberDescriptor("COUNT", "COUNT", 0x7642dbf63a6e513aL, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/8521615295527145786");
  private final EnumerationDescriptor.MemberDescriptor myMember_MIN_0 = new EnumerationDescriptor.MemberDescriptor("MIN", "MIN", 0x7642dbf63a6e513dL, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/8521615295527145789");
  private final EnumerationDescriptor.MemberDescriptor myMember_MAX_0 = new EnumerationDescriptor.MemberDescriptor("MAX", "MAX", 0x7642dbf63a6e5141L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/8521615295527145793");
  private final EnumerationDescriptor.MemberDescriptor myMember_SUM_0 = new EnumerationDescriptor.MemberDescriptor("SUM", "SUM", 0x7642dbf63a6e5146L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/8521615295527145798");
  private final EnumerationDescriptor.MemberDescriptor myMember_AVG_0 = new EnumerationDescriptor.MemberDescriptor("AVG", "AVG", 0x7642dbf63a6fa3d6L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/8521615295527232470");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x26d1395b1ee643adL, 0xb522c0cdd699ded3L, 0x7642dbf63a6e5138L, 0x7642dbf63a6e513aL, 0x7642dbf63a6e513dL, 0x7642dbf63a6e5141L, 0x7642dbf63a6e5146L, 0x7642dbf63a6fa3d6L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_COUNT_0, myMember_MIN_0, myMember_MAX_0, myMember_SUM_0, myMember_AVG_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "COUNT":
        return myMember_COUNT_0;
      case "MIN":
        return myMember_MIN_0;
      case "MAX":
        return myMember_MAX_0;
      case "SUM":
        return myMember_SUM_0;
      case "AVG":
        return myMember_AVG_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
