package QueryLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Operator extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Operator() {
    super(0x26d1395b1ee643adL, 0xb522c0cdd699ded3L, 0x11100ee737470ff9L, "Operator", "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/1229499084499783673");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_EQUALS_0 = new EnumerationDescriptor.MemberDescriptor("EQUALS", "==", 0x11100ee737470ffaL, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/1229499084499783674");
  private final EnumerationDescriptor.MemberDescriptor myMember_GREATER_0 = new EnumerationDescriptor.MemberDescriptor("GREATER", ">", 0x11100ee737470ffcL, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/1229499084499783676");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOWER_0 = new EnumerationDescriptor.MemberDescriptor("LOWER", "<", 0x11100ee737471008L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/1229499084499783688");
  private final EnumerationDescriptor.MemberDescriptor myMember_GREATER_EQUAL_0 = new EnumerationDescriptor.MemberDescriptor("GREATER_EQUAL", ">=", 0x11100ee73747100dL, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/1229499084499783693");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOWER_EQUAL_0 = new EnumerationDescriptor.MemberDescriptor("LOWER_EQUAL", "<=", 0x11100ee737471013L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/1229499084499783699");
  private final EnumerationDescriptor.MemberDescriptor myMember_NOT_EQUAL_0 = new EnumerationDescriptor.MemberDescriptor("NOT_EQUAL", "!=", 0x11100ee737471019L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/1229499084499783705");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x26d1395b1ee643adL, 0xb522c0cdd699ded3L, 0x11100ee737470ff9L, 0x11100ee737470ffaL, 0x11100ee737470ffcL, 0x11100ee737471008L, 0x11100ee73747100dL, 0x11100ee737471013L, 0x11100ee737471019L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_EQUALS_0, myMember_GREATER_0, myMember_LOWER_0, myMember_GREATER_EQUAL_0, myMember_LOWER_EQUAL_0, myMember_NOT_EQUAL_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "EQUALS":
        return myMember_EQUALS_0;
      case "GREATER":
        return myMember_GREATER_0;
      case "LOWER":
        return myMember_LOWER_0;
      case "GREATER_EQUAL":
        return myMember_GREATER_EQUAL_0;
      case "LOWER_EQUAL":
        return myMember_LOWER_EQUAL_0;
      case "NOT_EQUAL":
        return myMember_NOT_EQUAL_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
