package QueryLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TemporalUnit extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TemporalUnit() {
    super(0x26d1395b1ee643adL, 0xb522c0cdd699ded3L, 0x8073cf9a51b7603L, "TemporalUnit", "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/578498120054961667");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_SECONDS_0 = new EnumerationDescriptor.MemberDescriptor("SECONDS", "SECONDS", 0x8073cf9a51b7604L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/578498120054961668");
  private final EnumerationDescriptor.MemberDescriptor myMember_MINUTES_0 = new EnumerationDescriptor.MemberDescriptor("MINUTES", "MINUTES", 0x8073cf9a51f0666L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/578498120055195238");
  private final EnumerationDescriptor.MemberDescriptor myMember_HOURS_0 = new EnumerationDescriptor.MemberDescriptor("HOURS", "HOURS", 0x8073cf9a51e1edbL, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/578498120055135963");
  private final EnumerationDescriptor.MemberDescriptor myMember_DAYS_0 = new EnumerationDescriptor.MemberDescriptor("DAYS", "DAYS", 0x8073cf9a51b7608L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/578498120054961672");
  private final EnumerationDescriptor.MemberDescriptor myMember_WEEKS_0 = new EnumerationDescriptor.MemberDescriptor("WEEKS", "WEEKS", 0x8073cf9a51b7605L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/578498120054961669");
  private final EnumerationDescriptor.MemberDescriptor myMember_MONTHS_0 = new EnumerationDescriptor.MemberDescriptor("MONTHS", "MONTHS", 0x8073cf9a51b7611L, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/578498120054961681");
  private final EnumerationDescriptor.MemberDescriptor myMember_YEARS_0 = new EnumerationDescriptor.MemberDescriptor("YEARS", "YEARS", 0x8073cf9a51b760cL, "r:e2175f5d-85fc-4bdd-8ae1-8b72b7f266cc(QueryLanguage.structure)/578498120054961676");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x26d1395b1ee643adL, 0xb522c0cdd699ded3L, 0x8073cf9a51b7603L, 0x8073cf9a51b7604L, 0x8073cf9a51f0666L, 0x8073cf9a51e1edbL, 0x8073cf9a51b7608L, 0x8073cf9a51b7605L, 0x8073cf9a51b7611L, 0x8073cf9a51b760cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_SECONDS_0, myMember_MINUTES_0, myMember_HOURS_0, myMember_DAYS_0, myMember_WEEKS_0, myMember_MONTHS_0, myMember_YEARS_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_SECONDS_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "SECONDS":
        return myMember_SECONDS_0;
      case "MINUTES":
        return myMember_MINUTES_0;
      case "HOURS":
        return myMember_HOURS_0;
      case "DAYS":
        return myMember_DAYS_0;
      case "WEEKS":
        return myMember_WEEKS_0;
      case "MONTHS":
        return myMember_MONTHS_0;
      case "YEARS":
        return myMember_YEARS_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
