package ActorLanguage.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "ActorLanguage";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (concept.getName()) {
        case "Actor":
          return Collections.<NodeFactory>singletonList(new ActorFactory.NodeFactory_7694881003795581833());
        case "CreateEnvelope":
          return Collections.<NodeFactory>singletonList(new EnvelopeFactory.NodeFactory_2411303652493859819());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

}
